//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBooking
    {
        public int TouristID { get; set; }
        public string TouristName { get; set; }
        public string TouristPhone { get; set; }
        public string HotelName { get; set; }
        public string Place { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
        public string Offer { get; set; }
        public string ExtraInfo { get; set; }
        public int No_of_Days { get; set; }
    }
}
